<!DOCTYPE html>
<html><head><title>CreateRequestFailedExceptionAsync</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">7 references to CreateRequestFailedExceptionAsync</div><div class="rA">Azure.Analytics.Synapse.ManagedPrivateEndpoints (7)</div><div class="rG" id="Azure.Analytics.Synapse.ManagedPrivateEndpoints"><div class="rF"><div class="rN">Generated\ManagedPrivateEndpointsRestClient.cs (5)</div>
<a href="../Generated/ManagedPrivateEndpointsRestClient.cs.html#87"><b>87</b>throw await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(message.Response).ConfigureAwait(false);</a>
<a href="../Generated/ManagedPrivateEndpointsRestClient.cs.html#177"><b>177</b>throw await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(message.Response).ConfigureAwait(false);</a>
<a href="../Generated/ManagedPrivateEndpointsRestClient.cs.html#258"><b>258</b>throw await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(message.Response).ConfigureAwait(false);</a>
<a href="../Generated/ManagedPrivateEndpointsRestClient.cs.html#329"><b>329</b>throw await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(message.Response).ConfigureAwait(false);</a>
<a href="../Generated/ManagedPrivateEndpointsRestClient.cs.html#401"><b>401</b>throw await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(message.Response).ConfigureAwait(false);</a>
</div>
<div class="rF"><div class="rN">Shared\AutoRest\HttpPipelineExtensions.cs (1)</div>
<a href="../Shared/AutoRest/HttpPipelineExtensions.cs.html#66"><b>66</b>var exception = await clientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response).ConfigureAwait(false);</a>
</div>
<div class="rF"><div class="rN">Shared\Core\OperationInternalBase.cs (1)</div>
<a href="../Shared/Core/OperationInternalBase.cs.html#227"><b>227</b>? await _diagnostics.<i>CreateRequestFailedExceptionAsync</i>(response).ConfigureAwait(false)</a>
</div>
</div>
</body></html>