<!DOCTYPE html>
<html><head><title>_requestFailedException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">3 writes to _requestFailedException</div><div class="rA">Azure.Security.KeyVault.Administration (3)</div><div class="rG" id="Azure.Security.KeyVault.Administration"><div class="rF"><div class="rN">RestoreOperationInternal.cs (3)</div>
<a href="../RestoreOperationInternal.cs.html#210"><b>210</b><i>_requestFailedException</i> = ex;</a>
<a href="../RestoreOperationInternal.cs.html#215"><b>215</b><i>_requestFailedException</i> = new RequestFailedException(&quot;Unexpected Failure.&quot;, ex);</a>
<a href="../RestoreOperationInternal.cs.html#220"><b>220</b><i>_requestFailedException</i> = new RequestFailedException($&quot;{Error.Message}\nInnerError: {Error.InnerError}\nCode: {Error.Code}&quot;);</a>
</div>
</div>
<div class="rH">4 references to _requestFailedException</div><div class="rA">Azure.Security.KeyVault.Administration (4)</div><div class="rG" id="Azure.Security.KeyVault.Administration"><div class="rF"><div class="rN">RestoreOperationInternal.cs (4)</div>
<a href="../RestoreOperationInternal.cs.html#145"><b>145</b>if (<i>_requestFailedException</i> != null)</a>
<a href="../RestoreOperationInternal.cs.html#147"><b>147</b>throw <i>_requestFailedException</i>;</a>
<a href="../RestoreOperationInternal.cs.html#216"><b>216</b>throw <i>_requestFailedException</i>;</a>
<a href="../RestoreOperationInternal.cs.html#221"><b>221</b>throw <i>_requestFailedException</i>;</a>
</div>
</div>
</body></html>