<!DOCTYPE html>
<html><head><title>_requestFailedException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">3 writes to _requestFailedException</div><div class="rA">Azure.Security.KeyVault.Administration (3)</div><div class="rG" id="Azure.Security.KeyVault.Administration"><div class="rF"><div class="rN">BackupOperation.cs (3)</div>
<a href="../BackupOperation.cs.html#146"><b>146</b><i>_requestFailedException</i> = ex;</a>
<a href="../BackupOperation.cs.html#151"><b>151</b><i>_requestFailedException</i> = new RequestFailedException(&quot;Unexpected failure&quot;, ex);</a>
<a href="../BackupOperation.cs.html#156"><b>156</b><i>_requestFailedException</i> = new RequestFailedException($&quot;{_value.Error.Message}\nInnerError: {_value.Error.InnerError}\nCode: {_value.Error.Code}&quot;);</a>
</div>
</div>
<div class="rH">4 references to _requestFailedException</div><div class="rA">Azure.Security.KeyVault.Administration (4)</div><div class="rG" id="Azure.Security.KeyVault.Administration"><div class="rF"><div class="rN">BackupOperation.cs (4)</div>
<a href="../BackupOperation.cs.html#105"><b>105</b>if (<i>_requestFailedException</i> != null)</a>
<a href="../BackupOperation.cs.html#107"><b>107</b>throw <i>_requestFailedException</i>;</a>
<a href="../BackupOperation.cs.html#152"><b>152</b>throw <i>_requestFailedException</i>;</a>
<a href="../BackupOperation.cs.html#157"><b>157</b>throw <i>_requestFailedException</i>;</a>
</div>
</div>
</body></html>