<!DOCTYPE html>
<html><head><title>ClientDiagnostics</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">10 references to ClientDiagnostics</div><div class="rA">Azure.Core.Tests (10)</div><div class="rG" id="Azure.Core.Tests"><div class="rF"><div class="rN">FailedResponseExceptionTests.cs (10)</div>
<a href="../FailedResponseExceptionTests.cs.html#37"><b>37</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#95"><b>95</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#137"><b>137</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#155"><b>155</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#175"><b>175</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response, new ResponseError(&quot;CUSTOM CODE&quot;, null));</a>
<a href="../FailedResponseExceptionTests.cs.html#198"><b>198</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response, additionalInfo: new Dictionary&lt;string, string&gt;()</a>
<a href="../FailedResponseExceptionTests.cs.html#225"><b>225</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response, innerException: innerException);</a>
<a href="../FailedResponseExceptionTests.cs.html#264"><b>264</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#310"><b>310</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#331"><b>331</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
</div>
</div>
</body></html>