<!DOCTYPE html>
<html><head><title>CreateRequestFailedExceptionWithContent</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">3 references to CreateRequestFailedExceptionWithContent</div><div class="rA">Azure.Storage.Blobs.ChangeFeed (3)</div><div class="rG" id="Azure.Storage.Blobs.ChangeFeed"><div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (2)</div>
<a href="../Shared/Core/ClientDiagnostics.cs.html#103"><b>103</b>return <i>CreateRequestFailedExceptionWithContent</i>(response, message, content, errorCode, additionalInfo, innerException);</a>
<a href="../Shared/Core/ClientDiagnostics.cs.html#110"><b>110</b>return <i>CreateRequestFailedExceptionWithContent</i>(response, message, content, errorCode, additionalInfo, innerException);</a>
</div>
<div class="rF"><div class="rN">Shared\Errors.Clients.cs (1)</div>
<a href="../Shared/Errors.Clients.cs.html#109"><b>109</b>=&gt; clientDiagnostics.<i>CreateRequestFailedExceptionWithContent</i>(</a>
</div>
</div>
</body></html>