<!DOCTYPE html>
<html><head><title>Exception</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">1 write to Exception</div><div class="rA">Azure.Messaging.EventHubs (1)</div><div class="rG" id="Azure.Messaging.EventHubs"><div class="rF"><div class="rN">Processor\ProcessErrorEventArgs.cs (1)</div>
<a href="../Processor/ProcessErrorEventArgs.cs.html#62"><b>62</b><i>Exception</i> = exception;</a>
</div>
</div>
<div class="rH">11 references to Exception</div><div class="rA">Azure.Messaging.EventHubs.Processor.Tests (10)</div><div class="rG" id="Azure.Messaging.EventHubs.Processor.Tests"><div class="rF"><div class="rN">Processor\EventProcessorClientLiveTests.cs (2)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Processor/EventProcessorClientLiveTests.cs.html#640"><b>640</b>Assert.Fail($&quot;Processor Error Surfaced: ({ args.<i>Exception</i>.GetType().Name })[{ args.<i>Exception</i>.Message }]&quot;);</a>
</div>
<div class="rF"><div class="rN">Processor\EventProcessorClientTests.cs (2)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Processor/EventProcessorClientTests.cs.html#751"><b>751</b>Assert.That(capturedEventArgs.<i>Exception</i>, Is.InstanceOf&lt;DivideByZeroException&gt;().And.Message.EqualTo(exception.Message), &quot;The exception should have been propagated.&quot;);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Processor/EventProcessorClientTests.cs.html#784"><b>784</b>Assert.That(capturedEventArgs.<i>Exception</i>, Is.InstanceOf&lt;DivideByZeroException&gt;().And.Message.EqualTo(exception.Message), &quot;The exception should have been propagated.&quot;);</a>
</div>
<div class="rF"><div class="rN">Snippets\ReadMeSnippetsLiveTests.cs (1)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/ReadMeSnippetsLiveTests.cs.html#109"><b>109</b>await DoSomethingWithTheError(eventArgs.<i>Exception</i>);</a>
</div>
<div class="rF"><div class="rN">Snippets\Sample01_HelloWorldLiveTests.cs (1)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample01_HelloWorldLiveTests.cs.html#203"><b>203</b>Debug.WriteLine($&quot;\tException: { args.<i>Exception</i> }&quot;);</a>
</div>
<div class="rF"><div class="rN">Snippets\Sample03_EventProcessorHandlersLiveTests.cs (3)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample03_EventProcessorHandlersLiveTests.cs.html#381"><b>381</b>Debug.WriteLine($&quot;\tException: { args.<i>Exception</i> }&quot;);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample03_EventProcessorHandlersLiveTests.cs.html#474"><b>474</b>Debug.WriteLine($&quot;\tException: { args.<i>Exception</i> }&quot;);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample03_EventProcessorHandlersLiveTests.cs.html#488"><b>488</b>if (args.<i>Exception</i> is OutOfMemoryException)</a>
</div>
<div class="rF"><div class="rN">Snippets\Sample04_ProcessingEventsLiveTests.cs (1)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample04_ProcessingEventsLiveTests.cs.html#100"><b>100</b>Debug.WriteLine($&quot;\tException: { args.<i>Exception</i> }&quot;);</a>
</div>
</div>
<div class="rA">LineCounter (1)</div><div class="rG" id="LineCounter"><div class="rF"><div class="rN">BlobProcessorHost.cs (1)</div>
<a href="../../LineCounter/BlobProcessorHost.cs.html#57"><b>57</b>_logger.LogError(eventArgs.<i>Exception</i>, &quot;Error in &quot; + eventArgs.PartitionId);</a>
</div>
</div>
</body></html>