<!DOCTYPE html>
<html><head><title>CreateRequestFailedExceptionAsync</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">13 references to CreateRequestFailedExceptionAsync</div><div class="rA">Azure.Core.Tests (13)</div><div class="rG" id="Azure.Core.Tests"><div class="rF"><div class="rN">FailedResponseExceptionTests.cs (10)</div>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#37"><b>37</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response);</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#95"><b>95</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response);</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#137"><b>137</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response);</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#155"><b>155</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response);</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#175"><b>175</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response, new ResponseError(&quot;CUSTOM CODE&quot;, null));</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#198"><b>198</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response, additionalInfo: new Dictionary&lt;string, string&gt;()</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#225"><b>225</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response, innerException: innerException);</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#264"><b>264</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response);</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#310"><b>310</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response);</a>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#331"><b>331</b>RequestFailedException exception = await ClientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response);</a>
</div>
<div class="rF"><div class="rN">Shared\AutoRest\HttpPipelineExtensions.cs (1)</div>
<a href="../../Azure.Core.Tests/Shared/AutoRest/HttpPipelineExtensions.cs.html#66"><b>66</b>var exception = await clientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(response).ConfigureAwait(false);</a>
</div>
<div class="rF"><div class="rN">Shared\OperationInternalBase.cs (1)</div>
<a href="../../Azure.Core.Tests/Shared/OperationInternalBase.cs.html#227"><b>227</b>? await _diagnostics.<i>CreateRequestFailedExceptionAsync</i>(response).ConfigureAwait(false)</a>
</div>
<div class="rF"><div class="rN">TestClients\LowLevelClient\PetStoreClient.cs (1)</div>
<a href="../../Azure.Core.Tests/TestClients/LowLevelClient/PetStoreClient.cs.html#93"><b>93</b>throw await _clientDiagnostics.<i>CreateRequestFailedExceptionAsync</i>(message.Response).ConfigureAwait(false);</a>
</div>
</div>
</body></html>