<!DOCTYPE html>
<html><head><title>RequestFailedException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">11 references to RequestFailedException</div><div class="rA">Azure.Core (2)</div><div class="rG" id="Azure.Core"><div class="rF"><div class="rN">RequestFailedException.cs (1)</div>
<a href="../RequestFailedException.cs.html#53"><b>53</b>: <i>this</i>(status, message, null, innerException)</a>
</div>
<div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../Shared/ClientDiagnostics.cs.html#73"><b>73</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Core.Tests (1)</div><div class="rG" id="Azure.Core.Tests"><div class="rF"><div class="rN">FailedResponseExceptionTests.cs (1)</div>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#174"><b>174</b>var exception = new <i>RequestFailedException</i>(201, &quot;Message&quot;, &quot;Error&quot;, null);</a>
</div>
</div>
<div class="rA">Azure.Identity (1)</div><div class="rG" id="Azure.Identity"><div class="rF"><div class="rN">ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Identity/ClientDiagnostics.cs.html#73"><b>73</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Search.Documents (1)</div><div class="rG" id="Azure.Search.Documents"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Search.Documents/Shared/ClientDiagnostics.cs.html#73"><b>73</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Blobs (1)</div><div class="rG" id="Azure.Storage.Blobs"><div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Blobs/Shared/Core/ClientDiagnostics.cs.html#73"><b>73</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Blobs.Batch (1)</div><div class="rG" id="Azure.Storage.Blobs.Batch"><div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Blobs.Batch/Shared/Core/ClientDiagnostics.cs.html#73"><b>73</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Files.DataLake (2)</div><div class="rG" id="Azure.Storage.Files.DataLake"><div class="rF"><div class="rN">ErrorExtensions.cs (1)</div>
<a href="../../Azure.Storage.Files.DataLake/ErrorExtensions.cs.html#59"><b>59</b>return new <i>RequestFailedException</i>(</a>
</div>
<div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Files.DataLake/Shared/Core/ClientDiagnostics.cs.html#73"><b>73</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Files.Shares (1)</div><div class="rG" id="Azure.Storage.Files.Shares"><div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Files.Shares/Shared/Core/ClientDiagnostics.cs.html#73"><b>73</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Queues (1)</div><div class="rG" id="Azure.Storage.Queues"><div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Queues/Shared/Core/ClientDiagnostics.cs.html#73"><b>73</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
</body></html>