<!DOCTYPE html>
<html><head><title>_requestFailedException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">1 write to _requestFailedException</div><div class="rA">Azure.AI.TextAnalytics (1)</div><div class="rG" id="Azure.AI.TextAnalytics"><div class="rF"><div class="rN">HealthcareOperation.cs (1)</div>
<a href="../HealthcareOperation.cs.html#215"><b>215</b><i>_requestFailedException</i> = await ClientCommon.CreateExceptionForFailedOperationAsync(async, _diagnostics, _response, update.Value.Errors)</a>
</div>
</div>
<div class="rH">2 references to _requestFailedException</div><div class="rA">Azure.AI.TextAnalytics (2)</div><div class="rG" id="Azure.AI.TextAnalytics"><div class="rF"><div class="rN">HealthcareOperation.cs (2)</div>
<a href="../HealthcareOperation.cs.html#53"><b>53</b>throw <i>_requestFailedException</i>;</a>
<a href="../HealthcareOperation.cs.html#218"><b>218</b>throw <i>_requestFailedException</i>;</a>
</div>
</div>
</body></html>