<!DOCTYPE html>
<html><head><title>ErrorException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">2 instantiations of ErrorException</div><div class="rA">Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime (2)</div><div class="rG" id="Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime"><div class="rF"><div class="rN">Generated\PredictionOperations.cs (2)</div>
<a href="../Generated/PredictionOperations.cs.html#204"><b>204</b>var ex = new <i>ErrorException</i>(string.Format(&quot;Operation returned an invalid status code &#39;{0}&#39;&quot;, _statusCode));</a>
<a href="../Generated/PredictionOperations.cs.html#411"><b>411</b>var ex = new <i>ErrorException</i>(string.Format(&quot;Operation returned an invalid status code &#39;{0}&#39;&quot;, _statusCode));</a>
</div>
</div>
<div class="rH">7 references to ErrorException</div><div class="rA">Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime (6)</div><div class="rG" id="Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime"><div class="rF"><div class="rN">Generated\IPredictionOperations.cs (2)</div>
<a href="../Generated/IPredictionOperations.cs.html#54"><b>54</b>/// &lt;exception cref=&quot;<i>ErrorException</i>&quot;&gt;</a>
<a href="../Generated/IPredictionOperations.cs.html#93"><b>93</b>/// &lt;exception cref=&quot;<i>ErrorException</i>&quot;&gt;</a>
</div>
<div class="rF"><div class="rN">Generated\PredictionOperations.cs (4)</div>
<a href="../Generated/PredictionOperations.cs.html#82"><b>82</b>/// &lt;exception cref=&quot;<i>ErrorException</i>&quot;&gt;</a>
<a href="../Generated/PredictionOperations.cs.html#204"><b>204</b><i>var</i> ex = new ErrorException(string.Format(&quot;Operation returned an invalid status code &#39;{0}&#39;&quot;, _statusCode));</a>
<a href="../Generated/PredictionOperations.cs.html#289"><b>289</b>/// &lt;exception cref=&quot;<i>ErrorException</i>&quot;&gt;</a>
<a href="../Generated/PredictionOperations.cs.html#411"><b>411</b><i>var</i> ex = new ErrorException(string.Format(&quot;Operation returned an invalid status code &#39;{0}&#39;&quot;, _statusCode));</a>
</div>
</div>
<div class="rA">Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime.Tests (1)</div><div class="rG" id="Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime.Tests"><div class="rF"><div class="rN">Luis\PredictionTests.cs (1)</div>
<a href="../../Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime.Tests/Luis/PredictionTests.cs.html#208"><b>208</b>var ex = await Assert.ThrowsAsync&lt;<i>ErrorException</i>&gt;(async () =&gt;</a>
</div>
</div>
</body></html>